[package]
name = "dhcp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protocol = "3.2"
protocol-derive = "3.2"
eui48 = "1.1"
